// =======================================================
// Alpha India — Screener.in Style Dynamic Column Catalog
// Comprehensive Financial Database Ratios & Column Config
// =======================================================

export type ColumnCategory =
  | "most_used"
  | "quarter_pnl"
  | "annual_pnl"
  | "balance_sheet"
  | "cash_flow"
  | "ratios"
  | "price"
  | "shareholding"
  | "alpha_india";

export type ColumnSubCategory = "RECENT" | "PRECEDING" | "HISTORICAL";

export type ColumnFormat =
  | "currency_cr"
  | "currency_rs"
  | "percent"
  | "growth_percent"
  | "ratio"
  | "integer"
  | "multiple"
  | "badge"
  | "date"
  | "text";

export interface ColumnDefinition {
  id: string;
  label: string;
  shortLabel: string;
  category: ColumnCategory;
  subCategory: ColumnSubCategory;
  align: "left" | "center" | "right";
  minWidth?: string;
  description: string;
  format: ColumnFormat;
  sortKey: string;
  isCore?: boolean;
}

export const CATEGORY_TABS: { id: ColumnCategory; label: string }[] = [
  { id: "most_used", label: "Most Used" },
  { id: "quarter_pnl", label: "Quarter P&L" },
  { id: "annual_pnl", label: "Annual P&L" },
  { id: "balance_sheet", label: "Balance Sheet" },
  { id: "cash_flow", label: "Cash Flow" },
  { id: "ratios", label: "Ratios" },
  { id: "price", label: "Price & Technicals" },
  { id: "shareholding", label: "Shareholding" },
  { id: "alpha_india", label: "Alpha India / PEAD" },
];

export const ALL_AVAILABLE_COLUMNS: ColumnDefinition[] = [
  // -------------------------------------------------------------------------
  // 1. QUARTER P&L (RECENT)
  // -------------------------------------------------------------------------
  {
    id: "latest_quarter_sales",
    label: "Sales latest quarter",
    shortLabel: "Sales Qtr Rs.Cr.",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "115px",
    description: "Latest reported quarterly revenue (₹ Cr)",
    format: "currency_cr",
    sortKey: "latest_quarter_sales",
  },
  {
    id: "latest_quarter_net_profit",
    label: "Profit after tax latest quarter",
    shortLabel: "PAT Qtr Rs.Cr.",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "115px",
    description: "Latest reported quarterly net profit (₹ Cr)",
    format: "currency_cr",
    sortKey: "latest_quarter_net_profit",
  },
  {
    id: "opm_latest",
    label: "OPM %",
    shortLabel: "OPM %",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "90px",
    description: "Operating Profit Margin % for latest quarter",
    format: "percent",
    sortKey: "opm_latest",
  },
  {
    id: "operating_profit",
    label: "Operating Profit Qtr",
    shortLabel: "Op Profit Rs.Cr.",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "110px",
    description: "Operating Profit (EBITDA) for latest quarter",
    format: "currency_cr",
    sortKey: "operating_profit",
  },
  {
    id: "quarterly_sales_yoy",
    label: "YOY Quarterly sales growth",
    shortLabel: "Qtr Sales Var %",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "105px",
    description: "Year-over-Year quarterly sales growth %",
    format: "growth_percent",
    sortKey: "quarterly_sales_yoy",
  },
  {
    id: "quarterly_pat_yoy",
    label: "YOY Quarterly profit growth",
    shortLabel: "Qtr Profit Var %",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "110px",
    description: "Year-over-Year quarterly profit growth %",
    format: "growth_percent",
    sortKey: "quarterly_pat_yoy",
  },
  {
    id: "revenue_growth_qoq",
    label: "QoQ Sales growth",
    shortLabel: "QoQ Sales %",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "100px",
    description: "Sequential quarter-over-quarter sales growth %",
    format: "growth_percent",
    sortKey: "revenue_growth_qoq",
  },
  {
    id: "pat_growth_qoq",
    label: "QoQ Profit growth",
    shortLabel: "QoQ Profit %",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "100px",
    description: "Sequential quarter-over-quarter profit growth %",
    format: "growth_percent",
    sortKey: "pat_growth_qoq",
  },
  {
    id: "latest_quarter_eps",
    label: "EPS latest quarter",
    shortLabel: "EPS Qtr Rs.",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "95px",
    description: "Earnings per share for latest quarter (₹)",
    format: "currency_rs",
    sortKey: "latest_quarter_eps",
  },
  {
    id: "quarterly_eps_yoy",
    label: "YOY Quarterly EPS growth",
    shortLabel: "Qtr EPS Var %",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "right",
    minWidth: "100px",
    description: "Year-over-Year quarterly EPS variance %",
    format: "growth_percent",
    sortKey: "quarterly_eps_yoy",
  },

  // -------------------------------------------------------------------------
  // 2. ANNUAL P&L / TRAILING (PRECEDING)
  // -------------------------------------------------------------------------
  {
    id: "pat_12m",
    label: "Profit after tax (PAT 12M)",
    shortLabel: "PAT 12M Rs.Cr.",
    category: "annual_pnl",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "115px",
    description: "Trailing 12-Month Net Profit (₹ Cr)",
    format: "currency_cr",
    sortKey: "pat_12m",
  },
  {
    id: "eps_12m",
    label: "EPS 12M",
    shortLabel: "EPS 12M Rs.",
    category: "annual_pnl",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "100px",
    description: "Trailing 12-Month Earnings Per Share (₹)",
    format: "currency_rs",
    sortKey: "eps_12m",
  },
  {
    id: "sales_growth_ttm",
    label: "Sales growth (TTM)",
    shortLabel: "Sales growth %",
    category: "annual_pnl",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "105px",
    description: "Trailing 12-Month Sales Growth %",
    format: "growth_percent",
    sortKey: "sales_growth_ttm",
  },
  {
    id: "profit_growth_ttm",
    label: "Profit growth (TTM)",
    shortLabel: "Profit growth %",
    category: "annual_pnl",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "105px",
    description: "Trailing 12-Month Profit Growth %",
    format: "growth_percent",
    sortKey: "profit_growth_ttm",
  },
  {
    id: "opm_ttm",
    label: "OPM TTM",
    shortLabel: "OPM TTM %",
    category: "annual_pnl",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "95px",
    description: "Trailing 12-Month Operating Profit Margin %",
    format: "percent",
    sortKey: "opm_ttm",
  },

  // -------------------------------------------------------------------------
  // 3. HISTORICAL GROWTH (HISTORICAL)
  // -------------------------------------------------------------------------
  {
    id: "sales_growth_3yr",
    label: "Sales growth 3Years",
    shortLabel: "Sales Var 3Y %",
    category: "annual_pnl",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "110px",
    description: "Compounded Sales Growth over 3 Years %",
    format: "growth_percent",
    sortKey: "sales_growth_3yr",
  },
  {
    id: "sales_growth_5yr",
    label: "Sales growth 5Years",
    shortLabel: "Sales Var 5Y %",
    category: "annual_pnl",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "110px",
    description: "Compounded Sales Growth over 5 Years %",
    format: "growth_percent",
    sortKey: "sales_growth_5yr",
  },
  {
    id: "sales_growth_10yr",
    label: "Sales growth 10Years",
    shortLabel: "Sales Var 10Y %",
    category: "annual_pnl",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "110px",
    description: "Compounded Sales Growth over 10 Years %",
    format: "growth_percent",
    sortKey: "sales_growth_10yr",
  },
  {
    id: "profit_growth_3yr",
    label: "Profit growth 3Years",
    shortLabel: "Profit Var 3Y %",
    category: "annual_pnl",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "110px",
    description: "Compounded Profit Growth over 3 Years %",
    format: "growth_percent",
    sortKey: "profit_growth_3yr",
  },
  {
    id: "profit_growth_5yr",
    label: "Profit growth 5Years",
    shortLabel: "Profit Var 5Y %",
    category: "annual_pnl",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "110px",
    description: "Compounded Profit Growth over 5 Years %",
    format: "growth_percent",
    sortKey: "profit_growth_5yr",
  },
  {
    id: "profit_growth_10yr",
    label: "Profit growth 10Years",
    shortLabel: "Profit Var 10Y %",
    category: "annual_pnl",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "110px",
    description: "Compounded Profit Growth over 10 Years %",
    format: "growth_percent",
    sortKey: "profit_growth_10yr",
  },

  // -------------------------------------------------------------------------
  // 4. RATIOS & FINANCIAL QUALITY
  // -------------------------------------------------------------------------
  {
    id: "roce",
    label: "Return on capital employed (ROCE)",
    shortLabel: "ROCE %",
    category: "ratios",
    subCategory: "RECENT",
    align: "right",
    minWidth: "90px",
    description: "Return on Capital Employed (%)",
    format: "percent",
    sortKey: "roce",
  },
  {
    id: "roe",
    label: "Return on equity (ROE)",
    shortLabel: "ROE %",
    category: "ratios",
    subCategory: "RECENT",
    align: "right",
    minWidth: "90px",
    description: "Return on Equity (%)",
    format: "percent",
    sortKey: "roe",
  },
  {
    id: "debt_to_equity",
    label: "Debt to equity",
    shortLabel: "D/E",
    category: "ratios",
    subCategory: "RECENT",
    align: "right",
    minWidth: "80px",
    description: "Total Borrowings divided by Shareholder Equity",
    format: "ratio",
    sortKey: "debt_to_equity",
  },
  {
    id: "interest_coverage",
    label: "Interest Coverage",
    shortLabel: "Int. Cov",
    category: "ratios",
    subCategory: "RECENT",
    align: "right",
    minWidth: "90px",
    description: "EBIT divided by Interest Expense",
    format: "multiple",
    sortKey: "interest_coverage",
  },
  {
    id: "debtor_days",
    label: "Debtor days",
    shortLabel: "Debtor Days",
    category: "ratios",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "90px",
    description: "Average days taken to collect payments",
    format: "integer",
    sortKey: "debtor_days",
  },
  {
    id: "inventory_days",
    label: "Inventory days",
    shortLabel: "Inv Days",
    category: "ratios",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "90px",
    description: "Average days to turn over inventory",
    format: "integer",
    sortKey: "inventory_days",
  },
  {
    id: "cash_conversion_cycle",
    label: "Cash conversion cycle",
    shortLabel: "CCC Days",
    category: "ratios",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "90px",
    description: "Net operating cycle in days",
    format: "integer",
    sortKey: "cash_conversion_cycle",
  },
  {
    id: "cfo_to_pat",
    label: "CFO to PAT",
    shortLabel: "CFO/PAT",
    category: "ratios",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "90px",
    description: "Earnings quality ratio: Operating Cash Flow / Net Profit",
    format: "ratio",
    sortKey: "cfo_to_pat",
  },
  {
    id: "piotroski_score",
    label: "Piotroski score",
    shortLabel: "Piotroski",
    category: "ratios",
    subCategory: "RECENT",
    align: "center",
    minWidth: "85px",
    description: "9-Point financial health scoring system",
    format: "badge",
    sortKey: "piotroski_score",
  },
  {
    id: "health_score",
    label: "Alpha India Score",
    shortLabel: "AI Score",
    category: "ratios",
    subCategory: "RECENT",
    align: "center",
    minWidth: "85px",
    description: "Composite Alpha India Institutional Score (0-100)",
    format: "integer",
    sortKey: "health_score",
  },

  // -------------------------------------------------------------------------
  // 5. PRICE & VALUATION MULTIPLES
  // -------------------------------------------------------------------------
  {
    id: "current_price",
    label: "Current price (CMP)",
    shortLabel: "CMP Rs.",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "100px",
    description: "Current Market Price (₹)",
    format: "currency_rs",
    sortKey: "current_price",
  },
  {
    id: "market_cap",
    label: "Market Capitalization",
    shortLabel: "Mar Cap Rs.Cr.",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "115px",
    description: "Total Market Capitalization (₹ Cr)",
    format: "currency_cr",
    sortKey: "market_cap",
  },
  {
    id: "stock_pe",
    label: "Price to Earning (P/E)",
    shortLabel: "P/E",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "80px",
    description: "Price to Earnings valuation multiple",
    format: "ratio",
    sortKey: "stock_pe",
  },
  {
    id: "industry_pe",
    label: "Industry P/E",
    shortLabel: "Ind PE",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "80px",
    description: "Industry Median P/E",
    format: "ratio",
    sortKey: "industry_pe",
  },
  {
    id: "price_to_book",
    label: "Price to book value (P/B)",
    shortLabel: "CMP / BV",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "85px",
    description: "Current Market Price divided by Book Value",
    format: "ratio",
    sortKey: "price_to_book",
  },
  {
    id: "book_value",
    label: "Book Value",
    shortLabel: "B.V. Rs.",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "95px",
    description: "Book value per share (₹)",
    format: "currency_rs",
    sortKey: "book_value",
  },
  {
    id: "dividend_yield",
    label: "Dividend yield",
    shortLabel: "Div Yield %",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "90px",
    description: "Annual dividend payout yield %",
    format: "percent",
    sortKey: "dividend_yield",
  },
  {
    id: "peg_ratio",
    label: "PEG Ratio",
    shortLabel: "PEG",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "75px",
    description: "P/E divided by Growth rate",
    format: "ratio",
    sortKey: "peg_ratio",
  },
  {
    id: "return_3m",
    label: "Return over 3months",
    shortLabel: "3mth return %",
    category: "price",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "95px",
    description: "3-Month stock price return %",
    format: "growth_percent",
    sortKey: "return_3m",
  },
  {
    id: "return_6m",
    label: "Return over 6months",
    shortLabel: "6mth return %",
    category: "price",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "95px",
    description: "6-Month stock price return %",
    format: "growth_percent",
    sortKey: "return_6m",
  },
  {
    id: "return_1y",
    label: "Return over 1year",
    shortLabel: "1yr return %",
    category: "price",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "95px",
    description: "1-Year stock price return %",
    format: "growth_percent",
    sortKey: "return_1y",
  },
  {
    id: "stock_cagr_3yr",
    label: "Return over 3years (CAGR)",
    shortLabel: "Stock CAGR 3Y %",
    category: "price",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "110px",
    description: "3-Year Stock Price CAGR %",
    format: "growth_percent",
    sortKey: "stock_cagr_3yr",
  },
  {
    id: "stock_cagr_5yr",
    label: "Return over 5years (CAGR)",
    shortLabel: "Stock CAGR 5Y %",
    category: "price",
    subCategory: "HISTORICAL",
    align: "right",
    minWidth: "110px",
    description: "5-Year Stock Price CAGR %",
    format: "growth_percent",
    sortKey: "stock_cagr_5yr",
  },
  {
    id: "dma_50",
    label: "50 DMA",
    shortLabel: "50 DMA Rs.",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "95px",
    description: "50-Day Moving Average (₹)",
    format: "currency_rs",
    sortKey: "dma_50",
  },
  {
    id: "dma_200",
    label: "200 DMA",
    shortLabel: "200 DMA Rs.",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "95px",
    description: "200-Day Moving Average (₹)",
    format: "currency_rs",
    sortKey: "dma_200",
  },
  {
    id: "high_52_week",
    label: "52-Week High",
    shortLabel: "52W High Rs.",
    category: "price",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "95px",
    description: "52-Week High Price (₹)",
    format: "currency_rs",
    sortKey: "high_52_week",
  },
  {
    id: "low_52_week",
    label: "52-Week Low",
    shortLabel: "52W Low Rs.",
    category: "price",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "95px",
    description: "52-Week Low Price (₹)",
    format: "currency_rs",
    sortKey: "low_52_week",
  },
  {
    id: "distance_52w_high",
    label: "Distance from 52W High",
    shortLabel: "From 52W High %",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "110px",
    description: "Percentage distance from 52-week peak",
    format: "growth_percent",
    sortKey: "distance_52w_high",
  },
  {
    id: "rsi_14",
    label: "14-Day RSI",
    shortLabel: "RSI (14)",
    category: "price",
    subCategory: "RECENT",
    align: "right",
    minWidth: "80px",
    description: "14-Day Relative Strength Index (0-100)",
    format: "integer",
    sortKey: "rsi_14",
  },
  {
    id: "beta",
    label: "Beta",
    shortLabel: "Beta",
    category: "price",
    subCategory: "PRECEDING",
    align: "right",
    minWidth: "75px",
    description: "Stock Beta relative to Nifty 50",
    format: "ratio",
    sortKey: "beta",
  },
  {
    id: "current_stage",
    label: "Current Stage (Stan Weinstein)",
    shortLabel: "Stage",
    category: "price",
    subCategory: "RECENT",
    align: "center",
    minWidth: "105px",
    description: "Stan Weinstein / Minervini Stage (Stage 1 Base, Stage 2 Markup, Stage 3 Distribution, Stage 4 Downtrend)",
    format: "badge",
    sortKey: "current_stage",
  },
  {
    id: "sparkline",
    label: "Price Trend (30D)",
    shortLabel: "Trend",
    category: "price",
    subCategory: "RECENT",
    align: "center",
    minWidth: "90px",
    description: "30-day interactive price sparkline trajectory",
    format: "badge",
    sortKey: "return_3m",
  },

  // -------------------------------------------------------------------------
  // 6. BALANCE SHEET & CASH FLOW
  // -------------------------------------------------------------------------
  {
    id: "borrowings",
    label: "Borrowings",
    shortLabel: "Borrowings Rs.Cr.",
    category: "balance_sheet",
    subCategory: "RECENT",
    align: "right",
    minWidth: "115px",
    description: "Total Borrowings / Debt (₹ Cr)",
    format: "currency_cr",
    sortKey: "borrowings",
  },
  {
    id: "reserves",
    label: "Reserves",
    shortLabel: "Reserves Rs.Cr.",
    category: "balance_sheet",
    subCategory: "RECENT",
    align: "right",
    minWidth: "115px",
    description: "Total reserves & retained surplus (₹ Cr)",
    format: "currency_cr",
    sortKey: "reserves",
  },
  {
    id: "total_assets",
    label: "Total Assets",
    shortLabel: "Assets Rs.Cr.",
    category: "balance_sheet",
    subCategory: "RECENT",
    align: "right",
    minWidth: "115px",
    description: "Total Balance Sheet Assets (₹ Cr)",
    format: "currency_cr",
    sortKey: "total_assets",
  },
  {
    id: "cfo_latest",
    label: "Cash Flow from Operations (CFO)",
    shortLabel: "CFO Rs.Cr.",
    category: "cash_flow",
    subCategory: "RECENT",
    align: "right",
    minWidth: "110px",
    description: "Operating cash flow generated (₹ Cr)",
    format: "currency_cr",
    sortKey: "cfo_latest",
  },
  {
    id: "free_cash_flow",
    label: "Free Cash Flow (FCF)",
    shortLabel: "FCF Rs.Cr.",
    category: "cash_flow",
    subCategory: "RECENT",
    align: "right",
    minWidth: "110px",
    description: "Free cash flow available to equity holders (₹ Cr)",
    format: "currency_cr",
    sortKey: "free_cash_flow",
  },
  {
    id: "fcf_yield",
    label: "FCF Yield %",
    shortLabel: "FCF Yield %",
    category: "cash_flow",
    subCategory: "RECENT",
    align: "right",
    minWidth: "95px",
    description: "Free Cash Flow / Market Cap %",
    format: "percent",
    sortKey: "fcf_yield",
  },

  // -------------------------------------------------------------------------
  // 7. SHAREHOLDING
  // -------------------------------------------------------------------------
  {
    id: "promoter_holding",
    label: "Promoter holding",
    shortLabel: "Promoter %",
    category: "shareholding",
    subCategory: "RECENT",
    align: "right",
    minWidth: "90px",
    description: "Promoter ownership stake %",
    format: "percent",
    sortKey: "promoter_holding",
  },
  {
    id: "fii_holding",
    label: "FII holding",
    shortLabel: "FII %",
    category: "shareholding",
    subCategory: "RECENT",
    align: "right",
    minWidth: "85px",
    description: "Foreign Institutional Investor stake %",
    format: "percent",
    sortKey: "fii_holding",
  },
  {
    id: "dii_holding",
    label: "DII holding",
    shortLabel: "DII %",
    category: "shareholding",
    subCategory: "RECENT",
    align: "right",
    minWidth: "85px",
    description: "Domestic Institutional Investor stake %",
    format: "percent",
    sortKey: "dii_holding",
  },
  {
    id: "public_holding",
    label: "Public holding",
    shortLabel: "Public %",
    category: "shareholding",
    subCategory: "RECENT",
    align: "right",
    minWidth: "85px",
    description: "Public and retail shareholding %",
    format: "percent",
    sortKey: "public_holding",
  },

  // -------------------------------------------------------------------------
  // 8. ALPHA INDIA / PEAD PROPRIETARY
  // -------------------------------------------------------------------------
  {
    id: "pead_score",
    label: "PEAD Score",
    shortLabel: "PEAD Score",
    category: "alpha_india",
    subCategory: "RECENT",
    align: "center",
    minWidth: "100px",
    description: "Alpha India 100-Point PEAD Momentum Score",
    format: "integer",
    sortKey: "pead_score",
  },
  {
    id: "pead_tier",
    label: "PEAD Tier",
    shortLabel: "Tier",
    category: "alpha_india",
    subCategory: "RECENT",
    align: "center",
    minWidth: "90px",
    description: "Elite / Strong / Moderate classification",
    format: "badge",
    sortKey: "pead_score",
  },
  {
    id: "operating_leverage_ratio",
    label: "Operating Leverage Factor",
    shortLabel: "Op. Leverage",
    category: "alpha_india",
    subCategory: "RECENT",
    align: "center",
    minWidth: "100px",
    description: "PAT Growth divided by Sales Growth factor",
    format: "multiple",
    sortKey: "operating_leverage_ratio",
  },
  {
    id: "run_rate_beat_pct",
    label: "Run-Rate Beat %",
    shortLabel: "Beat %",
    category: "alpha_india",
    subCategory: "RECENT",
    align: "right",
    minWidth: "90px",
    description: "Quarterly outperformance vs 4-quarter average",
    format: "growth_percent",
    sortKey: "run_rate_beat_pct",
  },
  {
    id: "period",
    label: "Fiscal Period",
    shortLabel: "Period",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "left",
    minWidth: "85px",
    description: "Fiscal quarter or reporting period (e.g. Q3 FY26)",
    format: "badge",
    sortKey: "period",
  },
  {
    id: "announcement_date",
    label: "Announcement Date",
    shortLabel: "Announcement Date",
    category: "quarter_pnl",
    subCategory: "RECENT",
    align: "left",
    minWidth: "130px",
    description: "Date of financial result announcement or board meeting",
    format: "date",
    sortKey: "announcement_date",
  },
  {
    id: "athena_conviction_grade",
    label: "Athena Conviction",
    shortLabel: "Athena Grade",
    category: "alpha_india",
    subCategory: "RECENT",
    align: "center",
    minWidth: "105px",
    description: "Athena Omega 5-Gate Institutional Grade",
    format: "badge",
    sortKey: "athena_conviction_score",
  },
  {
    id: "broker_conviction_score",
    label: "Broker Conviction",
    shortLabel: "Broker Conviction",
    category: "alpha_india",
    subCategory: "RECENT",
    align: "center",
    minWidth: "120px",
    description: "Quantitative Institutional Brokerage Conviction Score (0-100)",
    format: "badge",
    sortKey: "broker_conviction_score",
  },
  {
    id: "consensus_upside_pct",
    label: "Consensus Upside %",
    shortLabel: "Consensus Upside",
    category: "alpha_india",
    subCategory: "RECENT",
    align: "right",
    minWidth: "120px",
    description: "Implied upside % to median institutional target price",
    format: "percent",
    sortKey: "consensus_upside_pct",
  },
];

// Most Used subset for the Screener.in "Most Used" tab
export const MOST_USED_COLUMN_IDS = [
  "current_price",
  "roce",
  "quarterly_pat_yoy",
  "eps_12m",
  "profit_growth_ttm",
  "opm_latest",
  "latest_quarter_sales",
  "latest_quarter_net_profit",
  "quarterly_sales_yoy",
  "stock_pe",
  "sales_growth_ttm",
  "market_cap",
  "debt_to_equity",
  "roe",
  "sales_growth_3yr",
  "sales_growth_5yr",
  "profit_growth_3yr",
  "profit_growth_5yr",
  "return_1y",
  "return_3m",
  "piotroski_score",
  "pead_score",
];

// Default selected columns matching Screener.in's peer comparison screenshot
export const DEFAULT_SCREENER_COLUMN_IDS = [
  "current_price",
  "roce",
  "quarterly_pat_yoy",
  "eps_12m",
  "profit_growth_ttm",
  "opm_latest",
  "latest_quarter_sales",
  "latest_quarter_net_profit",
  "quarterly_sales_yoy",
  "stock_pe",
  "sales_growth_ttm",
];

// Alternate Presets
export const COLUMN_PRESETS: { id: string; label: string; columnIds: string[] }[] = [
  {
    id: "screener_default",
    label: "Screener.in Default",
    columnIds: DEFAULT_SCREENER_COLUMN_IDS,
  },
  {
    id: "pead_momentum",
    label: "PEAD Momentum Radar",
    columnIds: [
      "pead_score",
      "latest_quarter_net_profit",
      "pat_growth_qoq",
      "latest_quarter_sales",
      "revenue_growth_qoq",
      "operating_leverage_ratio",
      "run_rate_beat_pct",
      "athena_conviction_grade",
    ],
  },
  {
    id: "institutional_brokerage",
    label: "Institutional Brokerage Radar",
    columnIds: [
      "current_price",
      "market_cap",
      "broker_conviction_score",
      "consensus_upside_pct",
      "quarterly_pat_yoy",
      "quarterly_sales_yoy",
      "roce",
      "stock_pe",
    ],
  },
  {
    id: "valuation_quality",
    label: "Valuation & Quality",
    columnIds: [
      "current_price",
      "market_cap",
      "stock_pe",
      "industry_pe",
      "price_to_book",
      "dividend_yield",
      "roce",
      "debt_to_equity",
      "piotroski_score",
    ],
  },
  {
    id: "cash_flow_growth",
    label: "Cash Flow & Compounding",
    columnIds: [
      "sales_growth_3yr",
      "sales_growth_5yr",
      "profit_growth_3yr",
      "profit_growth_5yr",
      "cfo_latest",
      "free_cash_flow",
      "fcf_yield",
      "cfo_to_pat",
    ],
  },
];

export const QUARTERLY_STORAGE_KEY = "alpha_india_quarterly_selected_columns_v1";
export const GROWTH_SCREENER_STORAGE_KEY = "alpha_india_growth_screener_columns_v1";

export function loadSavedColumns(key: string = QUARTERLY_STORAGE_KEY): string[] {
  if (typeof window === "undefined") return DEFAULT_SCREENER_COLUMN_IDS;
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return DEFAULT_SCREENER_COLUMN_IDS;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) {
      return parsed;
    }
    return DEFAULT_SCREENER_COLUMN_IDS;
  } catch {
    return DEFAULT_SCREENER_COLUMN_IDS;
  }
}

export function saveColumns(columnIds: string[], key: string = QUARTERLY_STORAGE_KEY): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(key, JSON.stringify(columnIds));
  } catch (err) {
    console.error("Failed to save column configuration to localStorage:", err);
  }
}

export function resetDefaultColumns(key: string = QUARTERLY_STORAGE_KEY): string[] {
  if (typeof window !== "undefined") {
    try {
      localStorage.removeItem(key);
    } catch {
      // ignore
    }
  }
  return DEFAULT_SCREENER_COLUMN_IDS;
}
