"""baseline_schema

Revision ID: 68a83f14be70
Revises: 
Create Date: 2026-09-21 14:31:50.451081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68a83f14be70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive_yahoo_financial_import_progress')
    op.drop_table('archive_yahoo_quarterly_results')
    op.drop_table('archive_yahoo_company_market_metrics')
    op.drop_index(op.f('ix_esca_archived_at'), table_name='early_stage_candidate_archive')
    op.drop_index(op.f('ix_esca_company_name'), table_name='early_stage_candidate_archive')
    op.drop_table('early_stage_candidate_archive')
    op.drop_table('archive_yahoo_financial_import_audit')
    op.drop_table('archive_yahoo_financial_import_queue')
    op.drop_index(op.f('idx_alert_channel_configs_user_id'), table_name='alert_channel_configs')
    op.drop_index(op.f('ix_alert_channel_configs_channel'), table_name='alert_channel_configs')
    op.create_index(op.f('ix_alert_channel_configs_channel'), 'alert_channel_configs', ['channel'], unique=False)
    op.create_index(op.f('ix_alert_channel_configs_user_id'), 'alert_channel_configs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_announcements_radar_absorption'), table_name='announcements_radar')
    op.drop_index(op.f('ix_announcements_radar_trend'), table_name='announcements_radar')
    op.drop_index(op.f('ix_announcements_radar_vertical'), table_name='announcements_radar')
    op.create_index(op.f('ix_announcements_radar_absorption_status'), 'announcements_radar', ['absorption_status'], unique=False)
    op.create_index(op.f('ix_announcements_radar_announcement_date'), 'announcements_radar', ['announcement_date'], unique=False)
    op.create_index(op.f('ix_announcements_radar_recommendation'), 'announcements_radar', ['recommendation'], unique=False)
    op.create_index(op.f('ix_announcements_radar_recommendation_date'), 'announcements_radar', ['recommendation_date'], unique=False)
    op.create_index(op.f('ix_announcements_radar_trend_regime'), 'announcements_radar', ['trend_regime'], unique=False)
    op.create_index(op.f('ix_announcements_radar_vertical_archetype'), 'announcements_radar', ['vertical_archetype'], unique=False)
    op.create_index('ix_announcements_radar_vertical_regime', 'announcements_radar', ['vertical_archetype', 'trend_regime'], unique=False)
    op.alter_column('companies', 'is_provisional',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_companies_symbol'), table_name='companies')
    op.drop_index(op.f('idx_companies_updated_at'), table_name='companies')
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_index(op.f('ix_companies_updated_at'), 'companies', ['updated_at'], unique=False)
    op.drop_column('companies', 'face_value')
    op.alter_column('early_stage_candidate', 'sentiment',
               existing_type=postgresql.ENUM('positive', 'neutral', 'negative', name='sentiment_enum'),
               nullable=True,
               existing_server_default=sa.text("'neutral'::sentiment_enum"))
    op.alter_column('early_stage_candidate', 'status',
               existing_type=postgresql.ENUM('suggested', 'imported', 'ignored', name='candidate_status'),
               nullable=True,
               existing_server_default=sa.text("'suggested'::candidate_status"))
    op.alter_column('early_stage_candidate', 'is_listed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_esc_company_name'), table_name='early_stage_candidate')
    op.drop_index(op.f('ix_esc_is_listed'), table_name='early_stage_candidate')
    op.drop_index(op.f('ix_esc_source'), table_name='early_stage_candidate')
    op.drop_index(op.f('ix_esc_status'), table_name='early_stage_candidate')
    op.create_index(op.f('ix_early_stage_candidate_id'), 'early_stage_candidate', ['id'], unique=False)
    op.create_index(op.f('ix_early_stage_candidate_is_listed'), 'early_stage_candidate', ['is_listed'], unique=False)
    op.drop_index(op.f('ix_esds_candidate_id'), table_name='early_stage_daily_summary')
    op.create_index(op.f('ix_early_stage_daily_summary_candidate_id'), 'early_stage_daily_summary', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_early_stage_daily_summary_id'), 'early_stage_daily_summary', ['id'], unique=False)
    op.create_index(op.f('ix_early_stage_import_log_candidate_id'), 'early_stage_import_log', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_early_stage_import_log_id'), 'early_stage_import_log', ['id'], unique=False)
    op.drop_index(op.f('ix_estc_fetched_at'), table_name='early_stage_temp_cache')
    op.drop_index(op.f('ix_estc_source'), table_name='early_stage_temp_cache')
    op.create_index(op.f('ix_early_stage_temp_cache_id'), 'early_stage_temp_cache', ['id'], unique=False)
    op.create_index(op.f('ix_early_stage_temp_cache_source'), 'early_stage_temp_cache', ['source'], unique=False)
    op.alter_column('filing_registry', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('filing_registry', 'symbol',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('filing_registry', 'exchange',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('filing_registry', 'pdf_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('filing_registry', 'pdf_local_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('filing_registry', 'download_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('filing_registry', 'parse_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('filing_registry', 'ai_processed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('filing_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_financial_import_progress_id'), 'financial_import_progress', ['id'], unique=False)
    op.alter_column('financial_metrics', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('financial_metrics', 'period',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('financial_metrics', 'revenue',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'revenue_growth',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'pat',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'pat_growth',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'ebitda_margin',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'roce',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'roe',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'debt_equity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'promoter_holding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'eps',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'eps_growth',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'pe_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'ai_score',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('financial_metrics_company_id_period_key'), 'financial_metrics', type_='unique')
    op.drop_index(op.f('idx_financial_company'), table_name='financial_metrics')
    op.drop_index(op.f('idx_financial_period'), table_name='financial_metrics')
    op.drop_index(op.f('idx_financial_score'), table_name='financial_metrics')
    op.create_index(op.f('ix_financial_metrics_company_id'), 'financial_metrics', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_metrics_id'), 'financial_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_financial_metrics_period'), 'financial_metrics', ['period'], unique=False)
    op.drop_constraint(op.f('financial_metrics_company_id_fkey'), 'financial_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'financial_metrics', 'companies', ['company_id'], ['id'])
    op.alter_column('monitoring_heartbeat', 'heartbeat_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_portfolios_user_id'), table_name='portfolios')
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.alter_column('quarterly_results', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quarterly_results', 'result_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_quarterly_results_fiscal_period'), 'quarterly_results', ['fiscal_period'], unique=False)
    op.create_index(op.f('ix_quarterly_results_period_end'), 'quarterly_results', ['period_end'], unique=False)
    op.create_unique_constraint('uq_quarterly_results_company_period', 'quarterly_results', ['company_id', 'period_end'])
    op.drop_column('quarterly_results', 'net_profit_margin')
    op.drop_column('quarterly_results', 'operating_margin')
    op.drop_index(op.f('idx_sgr_health_score'), table_name='screener_growth_records')
    op.drop_index(op.f('idx_sgr_market_cap'), table_name='screener_growth_records')
    op.drop_index(op.f('idx_sgr_pat_yoy'), table_name='screener_growth_records')
    op.drop_index(op.f('idx_sgr_roce'), table_name='screener_growth_records')
    op.drop_index(op.f('idx_sgr_sales_yoy'), table_name='screener_growth_records')
    op.drop_index(op.f('idx_sgr_stock_pe'), table_name='screener_growth_records')
    op.create_index(op.f('ix_screener_growth_records_health_score'), 'screener_growth_records', ['health_score'], unique=False)
    op.create_index(op.f('ix_screener_growth_records_market_cap'), 'screener_growth_records', ['market_cap'], unique=False)
    op.create_index(op.f('ix_screener_growth_records_quarterly_pat_yoy'), 'screener_growth_records', ['quarterly_pat_yoy'], unique=False)
    op.create_index(op.f('ix_screener_growth_records_quarterly_sales_yoy'), 'screener_growth_records', ['quarterly_sales_yoy'], unique=False)
    op.create_index(op.f('ix_screener_growth_records_roce'), 'screener_growth_records', ['roce'], unique=False)
    op.create_index(op.f('ix_screener_growth_records_stock_pe'), 'screener_growth_records', ['stock_pe'], unique=False)
    op.alter_column('system_settings', 'setting_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('system_settings', 'setting_value',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('system_settings', 'description')
    op.drop_column('system_settings', 'setting_type')
    op.drop_column('system_settings', 'updated_at')
    op.drop_index(op.f('idx_watchlists_user_id'), table_name='watchlists')
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.create_index(op.f('idx_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.add_column('system_settings', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('system_settings', sa.Column('setting_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('system_settings', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('system_settings', 'setting_value',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('system_settings', 'setting_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_screener_growth_records_stock_pe'), table_name='screener_growth_records')
    op.drop_index(op.f('ix_screener_growth_records_roce'), table_name='screener_growth_records')
    op.drop_index(op.f('ix_screener_growth_records_quarterly_sales_yoy'), table_name='screener_growth_records')
    op.drop_index(op.f('ix_screener_growth_records_quarterly_pat_yoy'), table_name='screener_growth_records')
    op.drop_index(op.f('ix_screener_growth_records_market_cap'), table_name='screener_growth_records')
    op.drop_index(op.f('ix_screener_growth_records_health_score'), table_name='screener_growth_records')
    op.create_index(op.f('idx_sgr_stock_pe'), 'screener_growth_records', ['stock_pe'], unique=False)
    op.create_index(op.f('idx_sgr_sales_yoy'), 'screener_growth_records', ['quarterly_sales_yoy'], unique=False)
    op.create_index(op.f('idx_sgr_roce'), 'screener_growth_records', ['roce'], unique=False)
    op.create_index(op.f('idx_sgr_pat_yoy'), 'screener_growth_records', ['quarterly_pat_yoy'], unique=False)
    op.create_index(op.f('idx_sgr_market_cap'), 'screener_growth_records', ['market_cap'], unique=False)
    op.create_index(op.f('idx_sgr_health_score'), 'screener_growth_records', ['health_score'], unique=False)
    op.add_column('quarterly_results', sa.Column('operating_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('quarterly_results', sa.Column('net_profit_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint('uq_quarterly_results_company_period', 'quarterly_results', type_='unique')
    op.drop_index(op.f('ix_quarterly_results_period_end'), table_name='quarterly_results')
    op.drop_index(op.f('ix_quarterly_results_fiscal_period'), table_name='quarterly_results')
    op.alter_column('quarterly_results', 'result_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('quarterly_results', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.create_index(op.f('idx_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.alter_column('monitoring_heartbeat', 'heartbeat_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'financial_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('financial_metrics_company_id_fkey'), 'financial_metrics', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_financial_metrics_period'), table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_id'), table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_company_id'), table_name='financial_metrics')
    op.create_index(op.f('idx_financial_score'), 'financial_metrics', [sa.literal_column('ai_score DESC')], unique=False)
    op.create_index(op.f('idx_financial_period'), 'financial_metrics', [sa.literal_column('period DESC')], unique=False)
    op.create_index(op.f('idx_financial_company'), 'financial_metrics', ['company_id'], unique=False)
    op.create_unique_constraint(op.f('financial_metrics_company_id_period_key'), 'financial_metrics', ['company_id', 'period'], postgresql_nulls_not_distinct=False)
    op.alter_column('financial_metrics', 'ai_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('financial_metrics', 'pe_ratio',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'eps_growth',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'eps',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'promoter_holding',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'debt_equity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'roe',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'roce',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'ebitda_margin',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'pat_growth',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'pat',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'revenue_growth',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'revenue',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('financial_metrics', 'period',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('financial_metrics', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_financial_import_progress_id'), table_name='financial_import_progress')
    op.alter_column('filing_registry', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('filing_registry', 'ai_processed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('filing_registry', 'parse_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('filing_registry', 'download_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('filing_registry', 'pdf_local_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('filing_registry', 'pdf_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('filing_registry', 'exchange',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('filing_registry', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('filing_registry', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_early_stage_temp_cache_source'), table_name='early_stage_temp_cache')
    op.drop_index(op.f('ix_early_stage_temp_cache_id'), table_name='early_stage_temp_cache')
    op.create_index(op.f('ix_estc_source'), 'early_stage_temp_cache', ['source'], unique=False)
    op.create_index(op.f('ix_estc_fetched_at'), 'early_stage_temp_cache', ['fetched_at'], unique=False)
    op.drop_index(op.f('ix_early_stage_import_log_id'), table_name='early_stage_import_log')
    op.drop_index(op.f('ix_early_stage_import_log_candidate_id'), table_name='early_stage_import_log')
    op.drop_index(op.f('ix_early_stage_daily_summary_id'), table_name='early_stage_daily_summary')
    op.drop_index(op.f('ix_early_stage_daily_summary_candidate_id'), table_name='early_stage_daily_summary')
    op.create_index(op.f('ix_esds_candidate_id'), 'early_stage_daily_summary', ['candidate_id'], unique=False)
    op.drop_index(op.f('ix_early_stage_candidate_is_listed'), table_name='early_stage_candidate')
    op.drop_index(op.f('ix_early_stage_candidate_id'), table_name='early_stage_candidate')
    op.create_index(op.f('ix_esc_status'), 'early_stage_candidate', ['status'], unique=False)
    op.create_index(op.f('ix_esc_source'), 'early_stage_candidate', ['source'], unique=False)
    op.create_index(op.f('ix_esc_is_listed'), 'early_stage_candidate', ['is_listed'], unique=False)
    op.create_index(op.f('ix_esc_company_name'), 'early_stage_candidate', ['company_name'], unique=False)
    op.alter_column('early_stage_candidate', 'is_listed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('early_stage_candidate', 'status',
               existing_type=postgresql.ENUM('suggested', 'imported', 'ignored', name='candidate_status'),
               nullable=False,
               existing_server_default=sa.text("'suggested'::candidate_status"))
    op.alter_column('early_stage_candidate', 'sentiment',
               existing_type=postgresql.ENUM('positive', 'neutral', 'negative', name='sentiment_enum'),
               nullable=False,
               existing_server_default=sa.text("'neutral'::sentiment_enum"))
    op.add_column('companies', sa.Column('face_value', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_updated_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.create_index(op.f('idx_companies_updated_at'), 'companies', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_companies_symbol'), 'companies', ['symbol'], unique=False)
    op.alter_column('companies', 'is_provisional',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_announcements_radar_vertical_regime', table_name='announcements_radar')
    op.drop_index(op.f('ix_announcements_radar_vertical_archetype'), table_name='announcements_radar')
    op.drop_index(op.f('ix_announcements_radar_trend_regime'), table_name='announcements_radar')
    op.drop_index(op.f('ix_announcements_radar_recommendation_date'), table_name='announcements_radar')
    op.drop_index(op.f('ix_announcements_radar_recommendation'), table_name='announcements_radar')
    op.drop_index(op.f('ix_announcements_radar_announcement_date'), table_name='announcements_radar')
    op.drop_index(op.f('ix_announcements_radar_absorption_status'), table_name='announcements_radar')
    op.create_index(op.f('ix_announcements_radar_vertical'), 'announcements_radar', ['vertical_archetype'], unique=False)
    op.create_index(op.f('ix_announcements_radar_trend'), 'announcements_radar', ['trend_regime'], unique=False)
    op.create_index(op.f('ix_announcements_radar_absorption'), 'announcements_radar', ['absorption_status'], unique=False)
    op.drop_index(op.f('ix_alert_channel_configs_user_id'), table_name='alert_channel_configs')
    op.drop_index(op.f('ix_alert_channel_configs_channel'), table_name='alert_channel_configs')
    op.create_index(op.f('ix_alert_channel_configs_channel'), 'alert_channel_configs', ['channel'], unique=True)
    op.create_index(op.f('idx_alert_channel_configs_user_id'), 'alert_channel_configs', ['user_id'], unique=False)
    op.create_table('archive_yahoo_financial_import_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('imported_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.VARCHAR(length=500), autoincrement=False, nullable=True)
    )
    op.create_table('archive_yahoo_financial_import_audit',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('quarter_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_revenue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_profit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_eps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duplicate_quarters', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('health_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('audited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('early_stage_candidate_archive',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tentative_ticker', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('mention_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trend_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False)
    )
    op.create_index(op.f('ix_esca_company_name'), 'early_stage_candidate_archive', ['company_name'], unique=False)
    op.create_index(op.f('ix_esca_archived_at'), 'early_stage_candidate_archive', ['archived_at'], unique=False)
    op.create_table('archive_yahoo_company_market_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cmp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_cap_category', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pe_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('industry_pe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pb_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('peg_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('roce', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('roe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('opm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('book_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividend_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('face_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('archive_yahoo_quarterly_results',
    sa.Column('archive_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fiscal_period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('result_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('operating_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interest_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interest_expense', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_interest_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_assets', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_equity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_debt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('book_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('operating_cash_flow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('free_cash_flow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue_growth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pat_growth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('roce', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('imported_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('archive_id', name=op.f('archive_yahoo_quarterly_results_pkey'))
    )
    op.create_table('archive_yahoo_financial_import_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_symbol', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eta_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
