"""
Curated Top 100 Pure Equity Scheme Master for Alpha India MF Radar
Sprint 39: Institutional Equity Universe
Filters: Direct - Growth only, Top AMCs, High AUM / Track Record.
Categories: Large Cap, Flexi Cap, Mid Cap, Small Cap, Large & Mid Cap, Multi Cap, Focused, Sectoral/Thematic, ELSS.
"""

from typing import List, Dict, Any

# Curated list of premier Direct - Growth equity schemes in India
# Mapped to AMFI scheme codes, benchmarks, and fund details
TOP_EQUITY_SCHEMES: List[Dict[str, Any]] = [
    # ── 1. FLEXI CAP FUNDS (Benchmark: NIFTY 500) ──
    {
        "scheme_code": "122639",
        "scheme_name": "Parag Parikh Flexi Cap Fund - Direct Plan - Growth",
        "amc_name": "PPFAS Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Rajeev Thakkar",
        "aum_cr": 78400.0,
        "ter": 0.61,
        "inception_year": 2013,
    },
    {
        "scheme_code": "118955",
        "scheme_name": "HDFC Flexi Cap Fund - Direct Plan - Growth",
        "amc_name": "HDFC Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Roshi Jain",
        "aum_cr": 64500.0,
        "ter": 0.78,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120166",
        "scheme_name": "Kotak Flexicap Fund - Direct Plan - Growth",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Harsha Upadhyaya",
        "aum_cr": 51200.0,
        "ter": 0.65,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120847",
        "scheme_name": "Quant Flexi Cap Fund - Direct Plan - Growth",
        "amc_name": "Quant Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Sandeep Tandon",
        "aum_cr": 8200.0,
        "ter": 0.77,
        "inception_year": 2013,
    },
    {
        "scheme_code": "118535",
        "scheme_name": "Franklin India Flexi Cap Fund - Direct Plan - Growth",
        "amc_name": "Franklin Templeton Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "R. Janakiraman",
        "aum_cr": 17800.0,
        "ter": 0.92,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120564",
        "scheme_name": "Aditya Birla Sun Life Flexi Cap Fund - Direct Plan - Growth",
        "amc_name": "Aditya Birla Sun Life Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Dhaval Joshi",
        "aum_cr": 22100.0,
        "ter": 0.84,
        "inception_year": 2013,
    },
    {
        "scheme_code": "118424",
        "scheme_name": "Bandhan Flexi Cap Fund - Direct Plan - Growth",
        "amc_name": "Bandhan Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Sachin Relekar",
        "aum_cr": 6800.0,
        "ter": 1.15,
        "inception_year": 2013,
    },
    {
        "scheme_code": "125354",
        "scheme_name": "Canara Robeco Flexi Cap Fund - Direct Plan - Growth",
        "amc_name": "Canara Robeco Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Shridatta Bhandwaldar",
        "aum_cr": 13400.0,
        "ter": 0.58,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120612",
        "scheme_name": "ICICI Prudential Flexicap Fund - Direct Plan - Growth",
        "amc_name": "ICICI Prudential Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Rajat Chandak",
        "aum_cr": 14900.0,
        "ter": 0.72,
        "inception_year": 2021,
    },
    {
        "scheme_code": "141838",
        "scheme_name": "JM Flexicap Fund - Direct Plan - Growth",
        "amc_name": "JM Financial Mutual Fund",
        "category": "Flexi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Satish Ramanathan",
        "aum_cr": 3600.0,
        "ter": 0.62,
        "inception_year": 2013,
    },

    # ── 2. LARGE CAP FUNDS (Benchmark: NIFTY 50 / NIFTY 100) ──
    {
        "scheme_code": "118968",
        "scheme_name": "HDFC Top 100 Fund - Direct Plan - Growth",
        "amc_name": "HDFC Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 100",
        "fund_manager": "Rahul Baijal",
        "aum_cr": 37200.0,
        "ter": 0.95,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120716",
        "scheme_name": "ICICI Prudential Bluechip Fund - Direct Plan - Growth",
        "amc_name": "ICICI Prudential Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 100",
        "fund_manager": "Anish Tawakley",
        "aum_cr": 58300.0,
        "ter": 0.88,
        "inception_year": 2013,
    },
    {
        "scheme_code": "119598",
        "scheme_name": "SBI Bluechip Fund - Direct Plan - Growth",
        "amc_name": "SBI Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 100",
        "fund_manager": "Sohini Andani",
        "aum_cr": 49100.0,
        "ter": 0.85,
        "inception_year": 2013,
    },
    {
        "scheme_code": "118632",
        "scheme_name": "Nippon India Large Cap Fund - Direct Plan - Growth",
        "amc_name": "Nippon India Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 100",
        "fund_manager": "Sailesh Raj Bhan",
        "aum_cr": 31400.0,
        "ter": 0.75,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120152",
        "scheme_name": "Kotak Bluechip Fund - Direct Plan - Growth",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 100",
        "fund_manager": "Harish Krishnan",
        "aum_cr": 9400.0,
        "ter": 0.62,
        "inception_year": 2013,
    },
    {
        "scheme_code": "118825",
        "scheme_name": "Mirae Asset Large Cap Fund - Direct Plan - Growth",
        "amc_name": "Mirae Asset Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 100",
        "fund_manager": "Gaurav Misra",
        "aum_cr": 39500.0,
        "ter": 0.64,
        "inception_year": 2013,
    },
    {
        "scheme_code": "125357",
        "scheme_name": "Canara Robeco Bluechip Equity Fund - Direct Plan - Growth",
        "amc_name": "Canara Robeco Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 100",
        "fund_manager": "Shridatta Bhandwaldar",
        "aum_cr": 14200.0,
        "ter": 0.49,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120465",
        "scheme_name": "Axis Bluechip Fund - Direct Plan - Growth",
        "amc_name": "Axis Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 50",
        "fund_manager": "Shreyash Devalkar",
        "aum_cr": 31200.0,
        "ter": 0.79,
        "inception_year": 2013,
    },
    {
        "scheme_code": "135783",
        "scheme_name": "Baroda BNP Paribas Large Cap Fund - Direct Plan - Growth",
        "amc_name": "Baroda BNP Paribas Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 100",
        "fund_manager": "Jitendra Sriram",
        "aum_cr": 2300.0,
        "ter": 0.95,
        "inception_year": 2013,
    },
    {
        "scheme_code": "131666",
        "scheme_name": "Tata Large Cap Fund - Direct Plan - Growth",
        "amc_name": "Tata Mutual Fund",
        "category": "Large Cap",
        "benchmark_index": "NIFTY 100",
        "fund_manager": "Rahul Singh",
        "aum_cr": 2500.0,
        "ter": 0.88,
        "inception_year": 2013,
    },

    # ── 3. MID CAP FUNDS (Benchmark: NIFTY MIDCAP 150) ──
    {
        "scheme_code": "118989",
        "scheme_name": "HDFC Mid-Cap Opportunities Fund - Direct Plan - Growth",
        "amc_name": "HDFC Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Chirag Setalvad",
        "aum_cr": 72400.0,
        "ter": 0.75,
        "inception_year": 2013,
    },
    {
        "scheme_code": "127042",
        "scheme_name": "Motilal Oswal Midcap Fund - Direct Plan - Growth",
        "amc_name": "Motilal Oswal Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Niket Shah",
        "aum_cr": 19800.0,
        "ter": 0.63,
        "inception_year": 2014,
    },
    {
        "scheme_code": "118668",
        "scheme_name": "Nippon India Growth Fund - Direct Plan - Growth",
        "amc_name": "Nippon India Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Rupesh Patel",
        "aum_cr": 33200.0,
        "ter": 0.81,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120843",
        "scheme_name": "Quant Mid Cap Fund - Direct Plan - Growth",
        "amc_name": "Quant Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Sandeep Tandon",
        "aum_cr": 10500.0,
        "ter": 0.68,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120153",
        "scheme_name": "Kotak Emerging Equity Fund - Direct Plan - Growth",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Pankaj Tibrewal",
        "aum_cr": 51200.0,
        "ter": 0.72,
        "inception_year": 2013,
    },
    {
        "scheme_code": "119777",
        "scheme_name": "SBI Magnum Midcap Fund - Direct Plan - Growth",
        "amc_name": "SBI Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Bhavin Vithlani",
        "aum_cr": 20500.0,
        "ter": 0.83,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120468",
        "scheme_name": "Axis Midcap Fund - Direct Plan - Growth",
        "amc_name": "Axis Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Shreyash Devalkar",
        "aum_cr": 26800.0,
        "ter": 0.59,
        "inception_year": 2013,
    },
    {
        "scheme_code": "125359",
        "scheme_name": "Canara Robeco Mid Cap Fund - Direct Plan - Growth",
        "amc_name": "Canara Robeco Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Pranav Gokhale",
        "aum_cr": 3200.0,
        "ter": 0.62,
        "inception_year": 2022,
    },
    {
        "scheme_code": "119178",
        "scheme_name": "Tata Mid Cap Growth Fund - Direct Plan - Growth",
        "amc_name": "Tata Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Satish Chandra Mishra",
        "aum_cr": 4900.0,
        "ter": 0.82,
        "inception_year": 2013,
    },
    {
        "scheme_code": "141840",
        "scheme_name": "Edelweiss Mid Cap Fund - Direct Plan - Growth",
        "amc_name": "Edelweiss Mutual Fund",
        "category": "Mid Cap",
        "benchmark_index": "NIFTY MIDCAP 150",
        "fund_manager": "Trideep Bhattacharya",
        "aum_cr": 6800.0,
        "ter": 0.54,
        "inception_year": 2013,
    },

    # ── 4. SMALL CAP FUNDS (Benchmark: NIFTY SMALLCAP 250) ──
    {
        "scheme_code": "118778",
        "scheme_name": "Nippon India Small Cap Fund - Direct Plan - Growth",
        "amc_name": "Nippon India Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "Samir Rachh",
        "aum_cr": 61200.0,
        "ter": 0.69,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120828",
        "scheme_name": "Quant Small Cap Fund - Direct Plan - Growth",
        "amc_name": "Quant Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "Sandeep Tandon",
        "aum_cr": 24500.0,
        "ter": 0.64,
        "inception_year": 2013,
    },
    {
        "scheme_code": "130503",
        "scheme_name": "HDFC Small Cap Fund - Direct Plan - Growth",
        "amc_name": "HDFC Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "Chirag Setalvad",
        "aum_cr": 34800.0,
        "ter": 0.68,
        "inception_year": 2013,
    },
    {
        "scheme_code": "125497",
        "scheme_name": "SBI Small Cap Fund - Direct Plan - Growth",
        "amc_name": "SBI Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "R. Srinivasan",
        "aum_cr": 32800.0,
        "ter": 0.67,
        "inception_year": 2013,
    },
    {
        "scheme_code": "145552",
        "scheme_name": "Tata Small Cap Fund - Direct Plan - Growth",
        "amc_name": "Tata Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "Chandraprakash Padiyar",
        "aum_cr": 9200.0,
        "ter": 0.42,
        "inception_year": 2018,
    },
    {
        "scheme_code": "147944",
        "scheme_name": "Bandhan Small Cap Fund - Direct Plan - Growth",
        "amc_name": "Bandhan Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "Manish Gunwani",
        "aum_cr": 6800.0,
        "ter": 0.45,
        "inception_year": 2020,
    },
    {
        "scheme_code": "120155",
        "scheme_name": "Kotak Small Cap Fund - Direct Plan - Growth",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "Pankaj Tibrewal",
        "aum_cr": 17800.0,
        "ter": 0.58,
        "inception_year": 2013,
    },
    {
        "scheme_code": "125351",
        "scheme_name": "Axis Small Cap Fund - Direct Plan - Growth",
        "amc_name": "Axis Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "Mayank Hyanki",
        "aum_cr": 23400.0,
        "ter": 0.55,
        "inception_year": 2013,
    },
    {
        "scheme_code": "118525",
        "scheme_name": "Franklin India Smaller Companies Fund - Direct Plan - Growth",
        "amc_name": "Franklin Templeton Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "R. Janakiraman",
        "aum_cr": 14200.0,
        "ter": 0.88,
        "inception_year": 2013,
    },
    {
        "scheme_code": "149262",
        "scheme_name": "Canara Robeco Small Cap Fund - Direct Plan - Growth",
        "amc_name": "Canara Robeco Mutual Fund",
        "category": "Small Cap",
        "benchmark_index": "NIFTY SMALLCAP 250",
        "fund_manager": "Shridatta Bhandwaldar",
        "aum_cr": 12800.0,
        "ter": 0.48,
        "inception_year": 2019,
    },

    # ── 5. MULTI CAP FUNDS (Benchmark: NIFTY 500 MULTICAP 50:25:25) ──
    {
        "scheme_code": "118650",
        "scheme_name": "Nippon India Multi Cap Fund - Direct Plan - Growth",
        "amc_name": "Nippon India Mutual Fund",
        "category": "Multi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Sailesh Raj Bhan",
        "aum_cr": 36100.0,
        "ter": 0.74,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120823",
        "scheme_name": "Quant Multi Cap Fund - Direct Plan - Growth",
        "amc_name": "Quant Mutual Fund",
        "category": "Multi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Sandeep Tandon",
        "aum_cr": 3800.0,
        "ter": 0.69,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120610",
        "scheme_name": "ICICI Prudential Multicap Fund - Direct Plan - Growth",
        "amc_name": "ICICI Prudential Mutual Fund",
        "category": "Multi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Sankaran Naren",
        "aum_cr": 14200.0,
        "ter": 0.82,
        "inception_year": 2013,
    },
    {
        "scheme_code": "149368",
        "scheme_name": "HDFC Multi Cap Fund - Direct Plan - Growth",
        "amc_name": "HDFC Mutual Fund",
        "category": "Multi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Gopal Agrawal",
        "aum_cr": 16400.0,
        "ter": 0.54,
        "inception_year": 2021,
    },
    {
        "scheme_code": "149258",
        "scheme_name": "Kotak Multicap Fund - Direct Plan - Growth",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "category": "Multi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Harsha Upadhyaya",
        "aum_cr": 13900.0,
        "ter": 0.44,
        "inception_year": 2021,
    },
    {
        "scheme_code": "141226",
        "scheme_name": "Mahindra Manulife Multi Cap Fund - Direct Plan - Growth",
        "amc_name": "Mahindra Manulife Mutual Fund",
        "category": "Multi Cap",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Krishna Sanghavi",
        "aum_cr": 4500.0,
        "ter": 0.58,
        "inception_year": 2017,
    },

    # ── 6. LARGE & MID CAP FUNDS (Benchmark: NIFTY LARGE MIDCAP 250) ──
    {
        "scheme_code": "120158",
        "scheme_name": "Mirae Asset Large & Mid Cap Fund - Direct Plan - Growth",
        "amc_name": "Mirae Asset Mutual Fund",
        "category": "Large & Mid Cap",
        "benchmark_index": "NIFTY LARGE MIDCAP 250",
        "fund_manager": "Neelesh Surana",
        "aum_cr": 41200.0,
        "ter": 0.65,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120841",
        "scheme_name": "Quant Large & Mid Cap Fund - Direct Plan - Growth",
        "amc_name": "Quant Mutual Fund",
        "category": "Large & Mid Cap",
        "benchmark_index": "NIFTY LARGE MIDCAP 250",
        "fund_manager": "Sandeep Tandon",
        "aum_cr": 3400.0,
        "ter": 0.72,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120158",
        "scheme_name": "Kotak Equity Opportunities Fund - Direct Plan - Growth",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "category": "Large & Mid Cap",
        "benchmark_index": "NIFTY LARGE MIDCAP 250",
        "fund_manager": "Harsha Upadhyaya",
        "aum_cr": 26800.0,
        "ter": 0.62,
        "inception_year": 2013,
    },
    {
        "scheme_code": "130498",
        "scheme_name": "HDFC Large and Mid Cap Fund - Direct Plan - Growth",
        "amc_name": "HDFC Mutual Fund",
        "category": "Large & Mid Cap",
        "benchmark_index": "NIFTY LARGE MIDCAP 250",
        "fund_manager": "Gopal Agrawal",
        "aum_cr": 22400.0,
        "ter": 0.81,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120593",
        "scheme_name": "ICICI Prudential Large & Mid Cap Fund - Direct Plan - Growth",
        "amc_name": "ICICI Prudential Mutual Fund",
        "category": "Large & Mid Cap",
        "benchmark_index": "NIFTY LARGE MIDCAP 250",
        "fund_manager": "Ihab Dalwai",
        "aum_cr": 16200.0,
        "ter": 0.78,
        "inception_year": 2013,
    },
    {
        "scheme_code": "119837",
        "scheme_name": "SBI Large & Midcap Fund - Direct Plan - Growth",
        "amc_name": "SBI Mutual Fund",
        "category": "Large & Mid Cap",
        "benchmark_index": "NIFTY LARGE MIDCAP 250",
        "fund_manager": "Saurabh Pant",
        "aum_cr": 25100.0,
        "ter": 0.79,
        "inception_year": 2013,
    },
    {
        "scheme_code": "146860",
        "scheme_name": "Bandhan Core Equity Fund - Direct Plan - Growth",
        "amc_name": "Bandhan Mutual Fund",
        "category": "Large & Mid Cap",
        "benchmark_index": "NIFTY LARGE MIDCAP 250",
        "fund_manager": "Manish Gunwani",
        "aum_cr": 4200.0,
        "ter": 0.72,
        "inception_year": 2013,
    },

    # ── 7. FOCUSED FUNDS (Benchmark: NIFTY 500) ──
    {
        "scheme_code": "119839",
        "scheme_name": "SBI Focused Equity Fund - Direct Plan - Growth",
        "amc_name": "SBI Mutual Fund",
        "category": "Focused",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "R. Srinivasan",
        "aum_cr": 34900.0,
        "ter": 0.71,
        "inception_year": 2013,
    },
    {
        "scheme_code": "118950",
        "scheme_name": "HDFC Focused 30 Fund - Direct Plan - Growth",
        "amc_name": "HDFC Mutual Fund",
        "category": "Focused",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Roshi Jain",
        "aum_cr": 13800.0,
        "ter": 0.62,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120601",
        "scheme_name": "ICICI Prudential Focused Equity Fund - Direct Plan - Growth",
        "amc_name": "ICICI Prudential Mutual Fund",
        "category": "Focused",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Anish Tawakley",
        "aum_cr": 10200.0,
        "ter": 0.69,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120839",
        "scheme_name": "Quant Focused Fund - Direct Plan - Growth",
        "amc_name": "Quant Mutual Fund",
        "category": "Focused",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Sandeep Tandon",
        "aum_cr": 1200.0,
        "ter": 0.64,
        "inception_year": 2013,
    },
    {
        "scheme_code": "131580",
        "scheme_name": "360 ONE Focused Equity Fund - Direct Plan - Growth",
        "amc_name": "360 ONE Mutual Fund",
        "category": "Focused",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Mayur Patel",
        "aum_cr": 7400.0,
        "ter": 0.78,
        "inception_year": 2014,
    },

    # ── 8. SECTORAL & THEMATIC FUNDS ──
    {
        "scheme_code": "120594",
        "scheme_name": "ICICI Prudential Technology Fund - Direct Plan - Growth",
        "amc_name": "ICICI Prudential Mutual Fund",
        "category": "Sectoral/Thematic",
        "benchmark_index": "NIFTY IT",
        "fund_manager": "Vaibhav Dusad",
        "aum_cr": 14200.0,
        "ter": 0.89,
        "inception_year": 2013,
    },
    {
        "scheme_code": "135790",
        "scheme_name": "Tata Digital India Fund - Direct Plan - Growth",
        "amc_name": "Tata Mutual Fund",
        "category": "Sectoral/Thematic",
        "benchmark_index": "NIFTY IT",
        "fund_manager": "Meeta Shetty",
        "aum_cr": 10500.0,
        "ter": 0.44,
        "inception_year": 2015,
    },
    {
        "scheme_code": "120578",
        "scheme_name": "SBI Technology Opportunities Fund - Direct Plan - Growth",
        "amc_name": "SBI Mutual Fund",
        "category": "Sectoral/Thematic",
        "benchmark_index": "NIFTY IT",
        "fund_manager": "Saurabh Pant",
        "aum_cr": 4200.0,
        "ter": 0.82,
        "inception_year": 2013,
    },
    {
        "scheme_code": "118770",
        "scheme_name": "Nippon India Power & Infra Fund - Direct Plan - Growth",
        "amc_name": "Nippon India Mutual Fund",
        "category": "Sectoral/Thematic",
        "benchmark_index": "NIFTY INFRASTRUCTURE",
        "fund_manager": "Sanjay Doshi",
        "aum_cr": 7200.0,
        "ter": 1.15,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120592",
        "scheme_name": "ICICI Prudential Infrastructure Fund - Direct Plan - Growth",
        "amc_name": "ICICI Prudential Mutual Fund",
        "category": "Sectoral/Thematic",
        "benchmark_index": "NIFTY INFRASTRUCTURE",
        "fund_manager": "Ihab Dalwai",
        "aum_cr": 6800.0,
        "ter": 0.98,
        "inception_year": 2013,
    },
    {
        "scheme_code": "118759",
        "scheme_name": "Nippon India Pharma Fund - Direct Plan - Growth",
        "amc_name": "Nippon India Mutual Fund",
        "category": "Sectoral/Thematic",
        "benchmark_index": "NIFTY PHARMA",
        "fund_manager": "Sailesh Raj Bhan",
        "aum_cr": 8100.0,
        "ter": 0.85,
        "inception_year": 2013,
    },
    {
        "scheme_code": "119783",
        "scheme_name": "SBI Healthcare Opportunities Fund - Direct Plan - Growth",
        "amc_name": "SBI Mutual Fund",
        "category": "Sectoral/Thematic",
        "benchmark_index": "NIFTY PHARMA",
        "fund_manager": "Rohit Shimpi",
        "aum_cr": 3900.0,
        "ter": 0.95,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120835",
        "scheme_name": "Quant Infrastructure Fund - Direct Plan - Growth",
        "amc_name": "Quant Mutual Fund",
        "category": "Sectoral/Thematic",
        "benchmark_index": "NIFTY INFRASTRUCTURE",
        "fund_manager": "Sandeep Tandon",
        "aum_cr": 4500.0,
        "ter": 0.72,
        "inception_year": 2013,
    },

    # ── 9. ELSS TAX SAVER FUNDS (Benchmark: NIFTY 500) ──
    {
        "scheme_code": "120833",
        "scheme_name": "Quant ELSS Tax Saver Fund - Direct Plan - Growth",
        "amc_name": "Quant Mutual Fund",
        "category": "ELSS",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Sandeep Tandon",
        "aum_cr": 11400.0,
        "ter": 0.62,
        "inception_year": 2013,
    },
    {
        "scheme_code": "135781",
        "scheme_name": "Mirae Asset ELSS Tax Saver Fund - Direct Plan - Growth",
        "amc_name": "Mirae Asset Mutual Fund",
        "category": "ELSS",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Neelesh Surana",
        "aum_cr": 25400.0,
        "ter": 0.58,
        "inception_year": 2015,
    },
    {
        "scheme_code": "120503",
        "scheme_name": "Axis ELSS- Tax Saver Fund - Direct Plan - Growth",
        "amc_name": "Axis Mutual Fund",
        "category": "ELSS",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Shreyash Devalkar",
        "aum_cr": 32800.0,
        "ter": 0.74,
        "inception_year": 2013,
    },
    {
        "scheme_code": "119060",
        "scheme_name": "HDFC ELSS Tax saver - Direct Plan - Growth",
        "amc_name": "HDFC Mutual Fund",
        "category": "ELSS",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Roshi Jain",
        "aum_cr": 16200.0,
        "ter": 0.85,
        "inception_year": 2013,
    },
    {
        "scheme_code": "149794",
        "scheme_name": "Parag Parikh ELSS Tax Saver Fund - Direct Plan - Growth",
        "amc_name": "PPFAS Mutual Fund",
        "category": "ELSS",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Rajeev Thakkar",
        "aum_cr": 4900.0,
        "ter": 0.65,
        "inception_year": 2022,
    },

    # ── 10. VALUE & CONTRA FUNDS (Benchmark: NIFTY 500) ──
    {
        "scheme_code": "119835",
        "scheme_name": "SBI Contra Fund - Direct Plan - Growth",
        "amc_name": "SBI Mutual Fund",
        "category": "Contra",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Dinesh Balachandran",
        "aum_cr": 39500.0,
        "ter": 0.71,
        "inception_year": 2013,
    },
    {
        "scheme_code": "119769",
        "scheme_name": "Kotak Contra Fund - Direct Plan - Growth",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "category": "Contra",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Shibani Kurian",
        "aum_cr": 4500.0,
        "ter": 0.65,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120608",
        "scheme_name": "ICICI Prudential Value Discovery Fund - Direct Plan - Growth",
        "amc_name": "ICICI Prudential Mutual Fund",
        "category": "Value",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Sankaran Naren",
        "aum_cr": 46200.0,
        "ter": 0.94,
        "inception_year": 2013,
    },
    {
        "scheme_code": "120837",
        "scheme_name": "Quant Value Fund - Direct Plan - Growth",
        "amc_name": "Quant Mutual Fund",
        "category": "Value",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Sandeep Tandon",
        "aum_cr": 2200.0,
        "ter": 0.68,
        "inception_year": 2021,
    },
    {
        "scheme_code": "118481",
        "scheme_name": "Bandhan Sterling Value Fund - Direct Plan - Growth",
        "amc_name": "Bandhan Mutual Fund",
        "category": "Value",
        "benchmark_index": "NIFTY 500",
        "fund_manager": "Daylynn Pinto",
        "aum_cr": 10500.0,
        "ter": 0.64,
        "inception_year": 2013,
    }
]
